name: Pull Request Checks

on:
  pull_request:

permissions: {}

jobs:
  common-checks:
    name: Common Checks
    permissions:
      contents: read
      pull-requests: read
    uses: nownabe/workflows/.github/workflows/pr.yaml@61479ab352f44180bef4dd8a4d9c19eb68dccb1a # v2.0.4

  result:
    name: Pull Request Checks
    if: always()
    needs:
      - common-checks
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions: {}
    steps:
      - name: Check job results
        env:
          HAS_FAILURE: ${{ contains(needs.*.result, 'failure') }}
          HAS_CANCELLED: ${{ contains(needs.*.result, 'cancelled') }}
        run: '[[ "$HAS_FAILURE" == "false" && "$HAS_CANCELLED" == "false" ]]'
