name: Pull Request Checks

on:
  workflow_call:

permissions: {}

jobs:
  filter:
    name: Filter
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: read
    outputs:
      changes: ${{ toJSON(steps.filter.outputs) }}
    steps:
      - id: filter
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: |
            github_workflow:
              - '.github/workflows/**'
              - '.github/actionlint.{yaml,yml}'
              - 'ghalint.{yaml,yml}'
              - '.ghalint.{yaml,yml}'
              - '.github/ghalint.{yaml,yml}'
              - 'zizmor.{yaml,yml}'
              - '.github/zizmor.{yaml,yml}'
            oxfmt:
              - '**/*.{ts,tsx,js,jsx,mts,cts,mjs,cjs}'
              - '**/*.{json,jsonc,json5}'
              - '**/*.{css,scss,less}'
              - '**/*.{yaml,yml,toml}'
              - '**/*.{html,vue,graphql}'
              - '**/*.{md,mdx}'
              - '.oxfmtrc*'
            renovate_config:
              - 'renovate.json5'
              - 'renovate.json'
              - '.renovaterc*'
              - '.github/renovate.json5'
              - '.github/renovate.json'
            shellcheck:
              - '**/*.sh'

  github-workflow:
    name: GitHub Workflow
    needs: filter
    if: ${{ fromJSON(needs.filter.outputs.changes).github_workflow == 'true' }}
    permissions:
      contents: read
    uses: ./.github/workflows/github-workflow.yaml

  oxfmt:
    name: oxfmt
    needs: filter
    if: ${{ fromJSON(needs.filter.outputs.changes).oxfmt == 'true' }}
    permissions:
      contents: read
    uses: ./.github/workflows/oxfmt.yaml

  renovate-config:
    name: Renovate Config
    needs: filter
    if: ${{ fromJSON(needs.filter.outputs.changes).renovate_config == 'true' }}
    permissions:
      contents: read
    uses: ./.github/workflows/renovate-config.yaml

  shellcheck:
    name: shellcheck
    needs: filter
    if: ${{ fromJSON(needs.filter.outputs.changes).shellcheck == 'true' }}
    permissions:
      contents: read
    uses: ./.github/workflows/shellcheck.yaml

  secret-scan:
    name: Secret Scan
    permissions:
      contents: read
    uses: ./.github/workflows/secret-scan.yaml
